// Code generated by sqlc. DO NOT EDIT.
// source: scraper.sql

package database

import (
	"context"

	"github.com/lib/pq"
)

const listScraperForType = `-- name: ListScraperForType :many
SELECT provider, priority, media_type, settings, enabled FROM scraper WHERE media_type @> $1 ORDER BY priority
`

func (q *Queries) ListScraperForType(ctx context.Context, mediaType []MediaType) ([]Scraper, error) {
	rows, err := q.db.QueryContext(ctx, listScraperForType, pq.Array(mediaType))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scraper
	for rows.Next() {
		var i Scraper
		if err := rows.Scan(
			&i.Provider,
			&i.Priority,
			pq.Array(&i.MediaType),
			&i.Settings,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
