---
kind: pipeline
type: docker
name: test

steps:
  - name: lint
    image: python:3.8.6-slim
    commands:
      - python -m pip install --upgrade pip
      - pip install flake8 gixy sqlfluff
      - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - sqlfluff lint database.sql
      - gixy nginx.conf
    
#  - name: test
#    image: python:3.8.6-slim
#    commands:
#      - apt-get update && apt-get install -y build-essential
#      - python -m pip install --upgrade pip
#      - pip install --no-cache-dir -r requirements_test.txt
#      - pytest

  - name: analysis
    image: registry.droso.io/ci/sonar:latest
    settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token
      sources: "src/"
      sonar_name: Zogwine
      sonar_key: Zogwine
      sonar_quality_enabled: true
      showProfiling: true

  - name: discord_notification
    image: appleboy/drone-discord
    when:
      status:
        - success
        - failure
    settings:
      webhook_id: 
        from_secret: webhook_id
      webhook_token:
        from_secret: webhook_token
      message: >
        {{#success build.status}}
        ✅ Build #{{build.number}} of `{{repo.name}}` succeeded.
        📝 Commit by {{commit.author}} on `{{commit.branch}}`:
        ```
        {{commit.message}}
        ```
        {{else}}
        ❌ Build #{{build.number}} of `{{repo.name}}` failed.
        📝 Commit by {{commit.author}} on `{{commit.branch}}`:
        ```
        {{commit.message}}
        ```
        {{/success}}

services:
  - name: mariadb
    image: mariadb:10.2
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: password

  - name: redis
    image: redis:6.0.8
    ports:
      - 6379

image_pull_secrets:
  - dockerconfigjson

trigger:
  event: 
    - push
    - pull_request

---
kind: pipeline
type: docker
name: deploy

steps:
  - name: deploy
    image: node:14-buster-slim
    commands:
      - apt-get update
      - apt-get install -y curl git
      - curl -fsSL https://get.docker.com | bash
      - curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose
      - npm install -g @quasar/cli
      - docker-compose -f /drone/prod/docker-compose.yml -p Zogwine down
      - cp /drone/prod/docker-compose.yml /drone/docker-compose.yml
      - ls /drone
      - rm -rf /drone/prod/*
      - cp -R /drone/src/* /drone/prod/
      - ls /drone/prod
      - git clone --depth 1 https://github.com/drosoCode/Zogwine_UI /drone/Zogwine_UI
      - cd /drone/Zogwine_UI && npm i --save-dev && quasar build
      - mkdir -p /drone/prod/static/
      - cp -R /drone/Zogwine_UI/dist/spa/* /drone/prod/static/
      - cp -R /drone/Zogwine_UI/pwa/* /drone/prod/static/
      - cp /drone/docker-compose.yml /drone/prod/docker-compose.yml
      - ls /drone/prod
      - docker-compose -f /drone/prod/docker-compose.yml -p Zogwine build
      - docker-compose -f /drone/prod/docker-compose.yml -p Zogwine up -d

    volumes:
      - name: prod
        path: /drone/prod
      - name: sock
        path: /var/run/docker.sock

  - name: discord_notification
    image: appleboy/drone-discord
    when:
      status:
        - success
        - failure
    settings:
      webhook_id:
        from_secret: webhook_id
      webhook_token:
        from_secret: webhook_token
      message: >
        {{#success build.status}}
        ✅ Deployment succeeded. 💾 Build #{{build.number}} for `{{repo.name}}`.
        {{else}}
        ❌ Deployment failed. 💾 Build #{{build.number}} for `{{repo.name}}`.
        {{/success}}

volumes:
  - name: prod
    host:
      path: /app/docker/run/Zogwine
  - name: sock
    host:
      path: /var/run/docker.sock

trigger:
  event:
  - promote
  target:
  - production

depends_on:
  - test

---
kind: secret
name: dockerconfigjson
get:
  path: kv/data/drone/registry/readonly
  name: dockerconfigjson

---
kind: secret
name: webhook_id
get:
  path: kv/data/discord/webhook/drone
  name: id

---
kind: secret
name: webhook_token
get:
  path: kv/data/discord/webhook/drone
  name: token

---
kind: secret
name: sonar_host
get:
  path: kv/data/sonarqube
  name: host

---
kind: secret
name: sonar_token
get:
  path: kv/data/sonarqube
  name: token

---
kind: signature
hmac: d1c250f1a603727aa014e0c75b7aeda7e4aedc041bda6f9f68907d2354957764

...
