// Code generated by 'yaegi extract github.com/Zogwine/Zogwine/internal/scraper/common'. DO NOT EDIT.

package symbol

import (
	"github.com/Zogwine/Zogwine/internal/scraper/common"
	"github.com/sirupsen/logrus"
	"reflect"
)

func init() {
	Symbols["github.com/Zogwine/Zogwine/internal/scraper/common/common"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Adaptation": reflect.ValueOf(common.Adaptation),
		"Canon":      reflect.ValueOf(common.Canon),
		"Filler":     reflect.ValueOf(common.Filler),
		"Mixed":      reflect.ValueOf(common.Mixed),

		// type definitions
		"FillerData":          reflect.ValueOf((*common.FillerData)(nil)),
		"FillerProvider":      reflect.ValueOf((*common.FillerProvider)(nil)),
		"FillerType":          reflect.ValueOf((*common.FillerType)(nil)),
		"MovieCollectionData": reflect.ValueOf((*common.MovieCollectionData)(nil)),
		"MovieData":           reflect.ValueOf((*common.MovieData)(nil)),
		"MovieProvider":       reflect.ValueOf((*common.MovieProvider)(nil)),
		"PersonData":          reflect.ValueOf((*common.PersonData)(nil)),
		"PersonDetails":       reflect.ValueOf((*common.PersonDetails)(nil)),
		"PersonProvider":      reflect.ValueOf((*common.PersonProvider)(nil)),
		"Provider":            reflect.ValueOf((*common.Provider)(nil)),
		"ScraperInfo":         reflect.ValueOf((*common.ScraperInfo)(nil)),
		"SearchData":          reflect.ValueOf((*common.SearchData)(nil)),
		"TVSData":             reflect.ValueOf((*common.TVSData)(nil)),
		"TVSEpisodeData":      reflect.ValueOf((*common.TVSEpisodeData)(nil)),
		"TVSSeasonData":       reflect.ValueOf((*common.TVSSeasonData)(nil)),
		"TVShowProvider":      reflect.ValueOf((*common.TVShowProvider)(nil)),
		"TagData":             reflect.ValueOf((*common.TagData)(nil)),
		"UpcomingData":        reflect.ValueOf((*common.UpcomingData)(nil)),

		// interface wrapper definitions
		"_FillerProvider": reflect.ValueOf((*_github_com_Zogwine_Zogwine_internal_scraper_common_FillerProvider)(nil)),
		"_MovieProvider":  reflect.ValueOf((*_github_com_Zogwine_Zogwine_internal_scraper_common_MovieProvider)(nil)),
		"_PersonProvider": reflect.ValueOf((*_github_com_Zogwine_Zogwine_internal_scraper_common_PersonProvider)(nil)),
		"_Provider":       reflect.ValueOf((*_github_com_Zogwine_Zogwine_internal_scraper_common_Provider)(nil)),
		"_TVShowProvider": reflect.ValueOf((*_github_com_Zogwine_Zogwine_internal_scraper_common_TVShowProvider)(nil)),
	}
}

// _github_com_Zogwine_Zogwine_internal_scraper_common_FillerProvider is an interface wrapper for FillerProvider type
type _github_com_Zogwine_Zogwine_internal_scraper_common_FillerProvider struct {
	IValue             interface{}
	WConfigure         func(ScraperID string, ScraperData string)
	WGetFiller         func() (common.FillerData, error)
	WNewFillerProvider func() common.FillerProvider
	WSearchFiller      func(name string) ([]common.SearchData, error)
	WSetup             func(config map[string]string, logger *logrus.Logger) error
}

func (W _github_com_Zogwine_Zogwine_internal_scraper_common_FillerProvider) Configure(ScraperID string, ScraperData string) {
	W.WConfigure(ScraperID, ScraperData)
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_common_FillerProvider) GetFiller() (common.FillerData, error) {
	return W.WGetFiller()
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_common_FillerProvider) NewFillerProvider() common.FillerProvider {
	return W.WNewFillerProvider()
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_common_FillerProvider) SearchFiller(name string) ([]common.SearchData, error) {
	return W.WSearchFiller(name)
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_common_FillerProvider) Setup(config map[string]string, logger *logrus.Logger) error {
	return W.WSetup(config, logger)
}

// _github_com_Zogwine_Zogwine_internal_scraper_common_MovieProvider is an interface wrapper for MovieProvider type
type _github_com_Zogwine_Zogwine_internal_scraper_common_MovieProvider struct {
	IValue              interface{}
	WConfigure          func(ScraperID string, ScraperData string)
	WGetMovie           func() (common.MovieData, error)
	WGetMovieCollection func() (common.MovieCollectionData, error)
	WGetMovieUpcoming   func() (common.UpcomingData, error)
	WListMoviePerson    func() ([]common.PersonData, error)
	WListMovieTag       func() ([]common.TagData, error)
	WSearchMovie        func(name string, year int) ([]common.SearchData, error)
	WSetup              func(config map[string]string, logger *logrus.Logger) error
}

func (W _github_com_Zogwine_Zogwine_internal_scraper_common_MovieProvider) Configure(ScraperID string, ScraperData string) {
	W.WConfigure(ScraperID, ScraperData)
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_common_MovieProvider) GetMovie() (common.MovieData, error) {
	return W.WGetMovie()
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_common_MovieProvider) GetMovieCollection() (common.MovieCollectionData, error) {
	return W.WGetMovieCollection()
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_common_MovieProvider) GetMovieUpcoming() (common.UpcomingData, error) {
	return W.WGetMovieUpcoming()
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_common_MovieProvider) ListMoviePerson() ([]common.PersonData, error) {
	return W.WListMoviePerson()
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_common_MovieProvider) ListMovieTag() ([]common.TagData, error) {
	return W.WListMovieTag()
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_common_MovieProvider) SearchMovie(name string, year int) ([]common.SearchData, error) {
	return W.WSearchMovie(name, year)
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_common_MovieProvider) Setup(config map[string]string, logger *logrus.Logger) error {
	return W.WSetup(config, logger)
}

// _github_com_Zogwine_Zogwine_internal_scraper_common_PersonProvider is an interface wrapper for PersonProvider type
type _github_com_Zogwine_Zogwine_internal_scraper_common_PersonProvider struct {
	IValue        interface{}
	WConfigure    func(ScraperID string, ScraperData string)
	WGetPerson    func() (common.PersonDetails, error)
	WSearchPerson func(name string) ([]common.SearchData, error)
	WSetup        func(config map[string]string, logger *logrus.Logger) error
}

func (W _github_com_Zogwine_Zogwine_internal_scraper_common_PersonProvider) Configure(ScraperID string, ScraperData string) {
	W.WConfigure(ScraperID, ScraperData)
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_common_PersonProvider) GetPerson() (common.PersonDetails, error) {
	return W.WGetPerson()
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_common_PersonProvider) SearchPerson(name string) ([]common.SearchData, error) {
	return W.WSearchPerson(name)
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_common_PersonProvider) Setup(config map[string]string, logger *logrus.Logger) error {
	return W.WSetup(config, logger)
}

// _github_com_Zogwine_Zogwine_internal_scraper_common_Provider is an interface wrapper for Provider type
type _github_com_Zogwine_Zogwine_internal_scraper_common_Provider struct {
	IValue     interface{}
	WConfigure func(ScraperID string, ScraperData string)
	WSetup     func(config map[string]string, logger *logrus.Logger) error
}

func (W _github_com_Zogwine_Zogwine_internal_scraper_common_Provider) Configure(ScraperID string, ScraperData string) {
	W.WConfigure(ScraperID, ScraperData)
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_common_Provider) Setup(config map[string]string, logger *logrus.Logger) error {
	return W.WSetup(config, logger)
}

// _github_com_Zogwine_Zogwine_internal_scraper_common_TVShowProvider is an interface wrapper for TVShowProvider type
type _github_com_Zogwine_Zogwine_internal_scraper_common_TVShowProvider struct {
	IValue          interface{}
	WConfigure      func(ScraperID string, ScraperData string)
	WGetTVS         func() (common.TVSData, error)
	WGetTVSEpisode  func(season int, episode int) (common.TVSEpisodeData, error)
	WGetTVSSeason   func(season int) (common.TVSSeasonData, error)
	WGetTVSUpcoming func() (common.UpcomingData, error)
	WListTVSPerson  func() ([]common.PersonData, error)
	WListTVSTag     func() ([]common.TagData, error)
	WSearchTVS      func(name string) ([]common.SearchData, error)
	WSetup          func(config map[string]string, logger *logrus.Logger) error
}

func (W _github_com_Zogwine_Zogwine_internal_scraper_common_TVShowProvider) Configure(ScraperID string, ScraperData string) {
	W.WConfigure(ScraperID, ScraperData)
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_common_TVShowProvider) GetTVS() (common.TVSData, error) {
	return W.WGetTVS()
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_common_TVShowProvider) GetTVSEpisode(season int, episode int) (common.TVSEpisodeData, error) {
	return W.WGetTVSEpisode(season, episode)
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_common_TVShowProvider) GetTVSSeason(season int) (common.TVSSeasonData, error) {
	return W.WGetTVSSeason(season)
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_common_TVShowProvider) GetTVSUpcoming() (common.UpcomingData, error) {
	return W.WGetTVSUpcoming()
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_common_TVShowProvider) ListTVSPerson() ([]common.PersonData, error) {
	return W.WListTVSPerson()
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_common_TVShowProvider) ListTVSTag() ([]common.TagData, error) {
	return W.WListTVSTag()
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_common_TVShowProvider) SearchTVS(name string) ([]common.SearchData, error) {
	return W.WSearchTVS(name)
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_common_TVShowProvider) Setup(config map[string]string, logger *logrus.Logger) error {
	return W.WSetup(config, logger)
}
