// Code generated by 'yaegi extract github.com/Zogwine/Zogwine/internal/scraper/types'. DO NOT EDIT.

package symbol

import (
	"github.com/Zogwine/Zogwine/internal/scraper/types"
	"reflect"
)

func init() {
	Symbols["github.com/Zogwine/Zogwine/internal/scraper/types/types"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Adaptation": reflect.ValueOf(types.Adaptation),
		"Canon":      reflect.ValueOf(types.Canon),
		"Filler":     reflect.ValueOf(types.Filler),
		"Mixed":      reflect.ValueOf(types.Mixed),

		// type definitions
		"FillerData":          reflect.ValueOf((*types.FillerData)(nil)),
		"FillerProvider":      reflect.ValueOf((*types.FillerProvider)(nil)),
		"FillerType":          reflect.ValueOf((*types.FillerType)(nil)),
		"MovieCollectionData": reflect.ValueOf((*types.MovieCollectionData)(nil)),
		"MovieData":           reflect.ValueOf((*types.MovieData)(nil)),
		"MovieProvider":       reflect.ValueOf((*types.MovieProvider)(nil)),
		"PersonData":          reflect.ValueOf((*types.PersonData)(nil)),
		"PersonDetailsData":   reflect.ValueOf((*types.PersonDetailsData)(nil)),
		"PersonProvider":      reflect.ValueOf((*types.PersonProvider)(nil)),
		"Provider":            reflect.ValueOf((*types.Provider)(nil)),
		"ScraperInfo":         reflect.ValueOf((*types.ScraperInfo)(nil)),
		"SearchData":          reflect.ValueOf((*types.SearchData)(nil)),
		"TVSData":             reflect.ValueOf((*types.TVSData)(nil)),
		"TVSEpisodeData":      reflect.ValueOf((*types.TVSEpisodeData)(nil)),
		"TVSSeasonData":       reflect.ValueOf((*types.TVSSeasonData)(nil)),
		"TVShowProvider":      reflect.ValueOf((*types.TVShowProvider)(nil)),
		"TagData":             reflect.ValueOf((*types.TagData)(nil)),
		"UpcomingData":        reflect.ValueOf((*types.UpcomingData)(nil)),

		// interface wrapper definitions
		"_FillerProvider": reflect.ValueOf((*_github_com_Zogwine_Zogwine_internal_scraper_types_FillerProvider)(nil)),
		"_MovieProvider":  reflect.ValueOf((*_github_com_Zogwine_Zogwine_internal_scraper_types_MovieProvider)(nil)),
		"_PersonProvider": reflect.ValueOf((*_github_com_Zogwine_Zogwine_internal_scraper_types_PersonProvider)(nil)),
		"_Provider":       reflect.ValueOf((*_github_com_Zogwine_Zogwine_internal_scraper_types_Provider)(nil)),
		"_TVShowProvider": reflect.ValueOf((*_github_com_Zogwine_Zogwine_internal_scraper_types_TVShowProvider)(nil)),
	}
}

// _github_com_Zogwine_Zogwine_internal_scraper_types_FillerProvider is an interface wrapper for FillerProvider type
type _github_com_Zogwine_Zogwine_internal_scraper_types_FillerProvider struct {
	IValue             interface{}
	WConfigure         func(ScraperID string, ScraperData string) error
	WGetFiller         func() (types.FillerData, error)
	WNewFillerProvider func() types.FillerProvider
	WSearchFiller      func(name string) ([]types.SearchData, error)
	WSetup             func(config map[string]interface{}) error
}

func (W _github_com_Zogwine_Zogwine_internal_scraper_types_FillerProvider) Configure(ScraperID string, ScraperData string) error {
	return W.WConfigure(ScraperID, ScraperData)
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_types_FillerProvider) GetFiller() (types.FillerData, error) {
	return W.WGetFiller()
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_types_FillerProvider) NewFillerProvider() types.FillerProvider {
	return W.WNewFillerProvider()
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_types_FillerProvider) SearchFiller(name string) ([]types.SearchData, error) {
	return W.WSearchFiller(name)
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_types_FillerProvider) Setup(config map[string]interface{}) error {
	return W.WSetup(config)
}

// _github_com_Zogwine_Zogwine_internal_scraper_types_MovieProvider is an interface wrapper for MovieProvider type
type _github_com_Zogwine_Zogwine_internal_scraper_types_MovieProvider struct {
	IValue              interface{}
	WConfigure          func(ScraperID string, ScraperData string) error
	WGetMovie           func() (types.MovieData, error)
	WGetMovieCollection func() (types.MovieCollectionData, error)
	WGetMovieUpcoming   func() (types.UpcomingData, error)
	WListMoviePerson    func() ([]types.PersonData, error)
	WListMovieTag       func() ([]types.TagData, error)
	WNewMovieProvider   func() types.MovieProvider
	WSearchMovie        func(name string) ([]types.SearchData, error)
	WSetup              func(config map[string]interface{}) error
}

func (W _github_com_Zogwine_Zogwine_internal_scraper_types_MovieProvider) Configure(ScraperID string, ScraperData string) error {
	return W.WConfigure(ScraperID, ScraperData)
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_types_MovieProvider) GetMovie() (types.MovieData, error) {
	return W.WGetMovie()
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_types_MovieProvider) GetMovieCollection() (types.MovieCollectionData, error) {
	return W.WGetMovieCollection()
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_types_MovieProvider) GetMovieUpcoming() (types.UpcomingData, error) {
	return W.WGetMovieUpcoming()
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_types_MovieProvider) ListMoviePerson() ([]types.PersonData, error) {
	return W.WListMoviePerson()
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_types_MovieProvider) ListMovieTag() ([]types.TagData, error) {
	return W.WListMovieTag()
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_types_MovieProvider) NewMovieProvider() types.MovieProvider {
	return W.WNewMovieProvider()
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_types_MovieProvider) SearchMovie(name string) ([]types.SearchData, error) {
	return W.WSearchMovie(name)
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_types_MovieProvider) Setup(config map[string]interface{}) error {
	return W.WSetup(config)
}

// _github_com_Zogwine_Zogwine_internal_scraper_types_PersonProvider is an interface wrapper for PersonProvider type
type _github_com_Zogwine_Zogwine_internal_scraper_types_PersonProvider struct {
	IValue             interface{}
	WConfigure         func(ScraperID string, ScraperData string) error
	WGetPersonDetails  func() (types.PersonDetailsData, error)
	WNewPersonProvider func() types.PersonProvider
	WSearchPerson      func(name string) ([]types.SearchData, error)
	WSetup             func(config map[string]interface{}) error
}

func (W _github_com_Zogwine_Zogwine_internal_scraper_types_PersonProvider) Configure(ScraperID string, ScraperData string) error {
	return W.WConfigure(ScraperID, ScraperData)
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_types_PersonProvider) GetPersonDetails() (types.PersonDetailsData, error) {
	return W.WGetPersonDetails()
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_types_PersonProvider) NewPersonProvider() types.PersonProvider {
	return W.WNewPersonProvider()
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_types_PersonProvider) SearchPerson(name string) ([]types.SearchData, error) {
	return W.WSearchPerson(name)
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_types_PersonProvider) Setup(config map[string]interface{}) error {
	return W.WSetup(config)
}

// _github_com_Zogwine_Zogwine_internal_scraper_types_Provider is an interface wrapper for Provider type
type _github_com_Zogwine_Zogwine_internal_scraper_types_Provider struct {
	IValue     interface{}
	WConfigure func(ScraperID string, ScraperData string) error
	WSetup     func(config map[string]interface{}) error
}

func (W _github_com_Zogwine_Zogwine_internal_scraper_types_Provider) Configure(ScraperID string, ScraperData string) error {
	return W.WConfigure(ScraperID, ScraperData)
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_types_Provider) Setup(config map[string]interface{}) error {
	return W.WSetup(config)
}

// _github_com_Zogwine_Zogwine_internal_scraper_types_TVShowProvider is an interface wrapper for TVShowProvider type
type _github_com_Zogwine_Zogwine_internal_scraper_types_TVShowProvider struct {
	IValue                 interface{}
	WConfigure             func(ScraperID string, ScraperData string) error
	WGetTVS                func() (types.TVSData, error)
	WGetTVSEpisode         func(season int, episode int) (types.TVSEpisodeData, error)
	WGetTVSSeason          func(season int) (types.TVSSeasonData, error)
	WGetTVSUpcomingEpisode func() (types.UpcomingData, error)
	WListTVSPerson         func() ([]types.PersonData, error)
	WListTVSTag            func() ([]types.TagData, error)
	WNewTVShowProvider     func() types.TVShowProvider
	WSearchTVS             func(name string) ([]types.SearchData, error)
	WSetup                 func(config map[string]interface{}) error
}

func (W _github_com_Zogwine_Zogwine_internal_scraper_types_TVShowProvider) Configure(ScraperID string, ScraperData string) error {
	return W.WConfigure(ScraperID, ScraperData)
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_types_TVShowProvider) GetTVS() (types.TVSData, error) {
	return W.WGetTVS()
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_types_TVShowProvider) GetTVSEpisode(season int, episode int) (types.TVSEpisodeData, error) {
	return W.WGetTVSEpisode(season, episode)
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_types_TVShowProvider) GetTVSSeason(season int) (types.TVSSeasonData, error) {
	return W.WGetTVSSeason(season)
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_types_TVShowProvider) GetTVSUpcomingEpisode() (types.UpcomingData, error) {
	return W.WGetTVSUpcomingEpisode()
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_types_TVShowProvider) ListTVSPerson() ([]types.PersonData, error) {
	return W.WListTVSPerson()
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_types_TVShowProvider) ListTVSTag() ([]types.TagData, error) {
	return W.WListTVSTag()
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_types_TVShowProvider) NewTVShowProvider() types.TVShowProvider {
	return W.WNewTVShowProvider()
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_types_TVShowProvider) SearchTVS(name string) ([]types.SearchData, error) {
	return W.WSearchTVS(name)
}
func (W _github_com_Zogwine_Zogwine_internal_scraper_types_TVShowProvider) Setup(config map[string]interface{}) error {
	return W.WSetup(config)
}
